### ISSUE TITLE
Signal Station - Traffic: no type can be selected

### ISSUE THREAD

**Issue by simon04** [OpenNauticalChart/josm#1]
Taken over from https://josm.openstreetmap.de/ticket/12346 (see there for more details + screenshots).

1. Select node w/o tags
2. Apply preset "Signal Station - Traffic (T21-T25)"
3. One cannot select a "Type"

This is due to https://github.com/OpenNauticalChart/josm/blob/a6955ced3362dfc5211c5903b20950e4520a82e7/INT-1-preset.xml#L4688 specifying a `default` values which is not listed.

**Comment by malcolmh** [comment]
Fixed

**Comment by simon04** [comment]
There are other lists affected as well (w/o claim of being complete):
* https://github.com/OpenNauticalChart/josm/blob/a931710f96f5cfb6ea09bdd80e3cbbc0257ae549/INT-1-preset.xml#L331
* https://github.com/OpenNauticalChart/josm/blob/a931710f96f5cfb6ea09bdd80e3cbbc0257ae549/INT-1-preset.xml#L4711

**Comment by malcolmh** [comment]
It would appear that multiselects don't like defaults

**Comment by Skippern** [comment]
Should consider if this need to be highlighted as a JOSM ticket. I would prefere to see defaults in Multiselects (preselected items).

**Comment by malcolmh** [comment]
Go ahead. There may some reason that it is the way it is, but raising a ticket will resolve that.

**Comment by Skippern** [comment]
I would have raised the ticket if I had been made aware of this yesterday, from today off and for the next weeks I am offshore with a very weak internet connection. If nobody raises the issue before I will do it when going back onshore

**Comment by malcolmh** [comment]
OK, I have opened the ticket: https://josm.openstreetmap.de/ticket/12387
