### ISSUE TITLE
Seamarks preset wrong values (seamark:type=distance_mark)

### ISSUE THREAD

**Issue by AdVerburg** [OpenNauticalChart/josm#10]
Steps to reproduce the problem:
1. Activate the Seamarks preset, ​https://raw.githubusercontent.com/OpenNauticalChart/josm/master/INT-1-preset.xml
2.  Insert a node in JOSM
3. Use the seamark preset for a Distance Mark (B25) to enter tag values. → with "Units for nautical charts:"

The expected result: A choice for "kilometres" | "hectometres" | "nautical_miles" | "statute_miles" | "metres" | "feet" as documented in ​https://wiki.openstreetmap.org/wiki/Seamarks/General_Attributes 

What happens instead? A choice for "kilometer" | "hectometer" | "nautical_miles" | "statute_miles" | "meters" | "feet". (American, not British English)

Changing the tag values (line numbers 309-314) in a user defined preset file to the "official"  tag values gives the expected behavior.
Redirected from https://josm.openstreetmap.de/ticket/18100#comment:1

**Comment by malcolmh** [comment]
Fixed
