### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by don-vip** [OpenNauticalChart/josm#11]
https://github.com/OpenNauticalChart/josm/blob/master/INT-1-preset.xml has dead links, can you please fix them?

Found HTTP error for https://wiki.openstreetmap.org/wiki/Seamarks/Attributes -> 404
Found HTTP error for https://wiki.openstreetmap.org/wiki/Seamarks/Objects -> 404
Found HTTP error for https://wiki.openstreetmap.org/wiki/Seamarks/Tag_Values -> 404

See https://josm.openstreetmap.de/ticket/17240

**Comment by malcolmh** [comment]
Done
