### ISSUE TITLE
dead links

### ISSUE THREAD

**Issue by Klumbumbus** [OpenNauticalChart/josm#12]
INT-1-preset.xml has these dead links:

https://www.iho.int/iho_pubs/standard/S-4/INT1_FR_Ed5_2012.pdf
https://www.nauticalcharts.noaa.gov/mcd/chart1/ChartNo1.pdf

**Comment by Skippern** [comment]
@malcolmh can you look into this, I have very limited internet connection for the moment, and will not be able to push to repo

**Comment by don-vip** [comment]
New link for INT1 is https://docs.iho.int/iho_pubs/standard/S-4/INT1_FR_Ed7_2019.pdf

**Comment by don-vip** [comment]
New link for ChartNo1 is https://nauticalcharts.noaa.gov/publications/docs/us-chart-1/ChartNo1.pdf

**Comment by malcolmh** [comment]
Fixed. Thanks Vincent!
