### ISSUE TITLE
Missing Icon Q/spar/horizontal

### ISSUE THREAD

**Issue by hakan9462** [OpenNauticalChart/josm#13]
Hello,

Missing Icon in Q/spar/horizontal

black_yellow
yellow_black
black_yellow_black
yellow_black_yellow

**Comment by malcolmh** [comment]
Could you please provide the node number of the object in question?

**Comment by hakan9462** [comment]
node :3529340707 for example

{
      "type": "Feature",
      "properties": {
        "@id": "node/3529340707",
        "seamark:beacon_cardinal:category": "south",
        "seamark:beacon_cardinal:colour": "yellow;black",
        "seamark:beacon_cardinal:colour_pattern": "horizontal",
        "seamark:beacon_cardinal:shape": "stake",
        "seamark:topmark:colour": "black",
        "seamark:topmark:shape": "2 cones down",
        "seamark:type": "beacon_cardinal"
      },

**Comment by malcolmh** [comment]
That looks OK: http://opennauticalchart.org/?permalink=true&zoom=17&lat=53.56037&lon=9.78112&seamarks=true&coordinate_grid=true

What do you think is missing?

**Comment by hakan9462** [comment]
Ok... but i can´t find the Icon on Github. When i go to the Icon folder and search for "Stake" (in Q folder) i do not find that icon.

**Comment by malcolmh** [comment]
Sorry, I was looking at the online map renderer, not the JOSM INT-1 preset. As I am not the author of this preset, I don't know how these icons are used.

Perhaps @skippern can help? Aun - are you alive & well?

**Comment by Skippern** [comment]
Unfortunately I will not be able to look into this for another couple of months. Feel free to take any existing icons and alter colours as needed and open a pull request, I will check and approve as I get time for it. Ping me in any PR so I see it quicker.

**Comment by Dirk--** [comment]
all in here !?

> black_yellow

https://github.com/OpenNauticalChart/josm/blob/master/icons/svg/Q/spar/horizontal/black_yellow.svg

> yellow_black

https://github.com/OpenNauticalChart/josm/blob/master/icons/svg/Q/spar/horizontal/yellow_black.svg

> black_yellow_black

https://github.com/OpenNauticalChart/josm/blob/master/icons/svg/Q/spar/horizontal/black_yellow_black.svg

> yellow_black_yellow

https://github.com/OpenNauticalChart/josm/blob/master/icons/svg/Q/spar/horizontal/yellow_black_yellow.svg
