### ISSUE TITLE
Invalid comment

### ISSUE THREAD

**Issue by tsmock** [OpenNauticalChart/josm#22]
The issue is located at https://github.com/OpenNauticalChart/josm/blob/master/INT-1-preset.xml#L15, see https://josm.openstreetmap.de/jenkins/job/JOSM-Integration/jdk=JDK8/9008/testReport/junit/org.openstreetmap.josm.gui.preferences.map/TaggingPresetPreferenceTestIT/Seamarks___https___github_com_OpenNauticalChart_josm_blob_master_INT_1_preset_xml/ .

For details on why `--` in a `<!-- comment -->` is an issue, please see https://www.w3.org/TR/REC-xml/#sec-comments .

**Comment by malcolmh** [comment]
Offending line removed
