### ISSUE TITLE
Dead icon links to http://dev.openseamap.org/

### ISSUE THREAD

**Issue by Klumbumbus** [OpenNauticalChart/josm#9]
see https://github.com/OpenSeaMap/josm/issues/25, https://github.com/OpenSeaMap/online_chart/issues/105 and https://josm.openstreetmap.de/ticket/17670

**Comment by malcolmh** [comment]
I have made copies of the missing icons in this repo and changed the references in both Presets_Hafen.xml & INT-1-preset.xml

**Comment by Klumbumbus** [comment]
Thanks.
